### ISSUE TITLE
sudo

### ISSUE THREAD

**Issue by till** [brokenpip3/setup-bats-libs#3]
Hey 👋🏼 , I am trying to use your action in a container, and it currently fails with `sudo: command not found`. I don't think it's necessary to use sudo in actions, would you object to removing it? I can make a PR too. :)

**Comment by brokenpip3** [comment]
hei :wave: 
yes indeed is not necessary, however when 2y ago I started this action the `BATS_LIB_PATH` was not aivable on bats, so I decided to install the libs under `/usr/lib` which it require sudo to move the files.

I'm trying to add cache in this PR: https://github.com/brokenpip3/setup-bats-libs/pull/2/ and at the same time remove sudo if not necessary, also by default. I may need a couple of weeks to restore and complete that PR and that features will also fix your sudo in a container issue.

**Comment by till** [comment]
OK, let me know if I can help, also thanks for considering it. :)

**Comment by brokenpip3** [comment]
Hey! :wave: 

I still want to support sudo-less libraries installation, I just released a new version that will install the bats binary as well since the original one that I used as companion will be broken soon due to node-12 deprecation: https://github.com/brokenpip3/setup-bats-libs/releases/tag/1.0.0

This gave to me the necessary enthusiasm to add also the option to not use sudo if the lib path is in $HOME, and the cache for the libs as well. Stay tuned :)

**Comment by brokenpip3** [comment]
should work now, let me know ;)
